dist: xenial
sudo: required
cache:
  directories:
      - $HOME/.m2
      - $HOME/.ccache
      - $HOME/downloads
  timeout: 1000
language: java
services:
      - docker

matrix:
   include:
      - os: linux
	arch: amd64
        env: PROJ=artoolkitplus OS=linux-armhf
        install: true
        script: ./ci/install-travis.sh
   allow_failures:
      - os: linux
        arch: arm64
        env: PROJ=artoolkitplus OS=linux-armhf
        install: true
        script: ./ci/install-travis.sh

