dist: xenial
sudo: required
cache:
  directories:
      - $HOME/.m2
      - $HOME/.ccache
      - $HOME/downloads
  timeout: 1000
services:
      - docker

matrix:
   include:
      - os: linux
        addons:
         apt:
          packages: maven
        arch: arm64
        env: PROJ=artoolkitplus linux-armhf
        install: true
        language: minimal
        script: "sudo add-apt-repository ppa:openjdk-r/ppa; sudo apt-get update; sudo apt install openjdk-11-jdk-headless; ./ci/install-travis.sh"
