dist: xenial
sudo: required
cache:
  directories:
      - $HOME/.m2
      - $HOME/.ccache
      - $HOME/downloads
  timeout: 1000
language: java
services:
      - docker

matrix:
   include:
      - os: linux
        env: PROJ=artoolkitplus linux-armhf
        install: true
        script: ./ci/install-travis.sh
